### ISSUE TITLE
Mandar correo  con la valoración de la conversación y la conversación

### ISSUE THREAD

**Issue by BraventMobile** [BraventIT/AeccApp#18]
Utilizando el servicio de envío de correos, debemos mandar la conversación si la valoración de esta es menos de 2 estrellas

**Comment by LuisM000** [comment]
¿Qué datos debería recibir el controller? ¿Cómo debería ser más o menos el modelo?

**Comment by Alfraso** [comment]
Hola Luis.

Gracias por el servicio de correo. Funciona de lujo 😉

Lo que necesitan los de AECC es que se envíe a una dirección concreta la conversación cuando el beneficiario la marca con menos de 4 estrellas (1,2 o 3).

Para ello, había pensado añadir una plantilla con keys tipo %CounterpartName%, %CounterpartSurname%, %Conversation%, etc. y luego reemplazarlos por los datos.

Ahora en una simple constante o variable, y en un futuro muy cercano, voy a añadir esas plantillas para que las devuelva el servicio y así las puedan editar ‘facilmente’ ¿?. Por lo que tampoco deberíamos matarnos en formatear el mensaje. Lo más importante es que lleve los keys adecuados

Los datos que debería llevar son:
- Nombre y Apellidos del beneficiario: Están en GlobalSetting.User
- Nombre y Apellidos del voluntario: Está en ChatService.ConversationCounterpart
- Valoración
- Conversación: Está en ChatService.GetConversationMessages() (eso de por si, es lo más importante y difícil de formatear)

Para poder compilar la app en Android, hace falta añadir una ruta a los sources de nugets:
https://www.myget.org/F/aad-clients-nightly/api/v3/index.json
Por necesidades de otros pluging necesitamos versiones muy actualizadas de las librerías support en Android, y la librería de autenticación (Microsoft.Identity.Client) solo funciona bien con las última librerías support en su versión alpha que se encuentra en su repositorio nightly.

Luis. Si tienes cualquier problema. dímelo.

**Comment by LuisM000** [comment]
Me alegro que funcionase bien :)
Si tengo alguna duda ya os comento.
