### ISSUE TITLE
Leer noticias desde origen actual 

### ISSUE THREAD

**Issue by BraventMobile** [BraventIT/AeccApp#20]
Utilizando HtmlAgilityPack podríamos buscar el nodo 'ul' con id 'noticias' para extraerlas de la página principal (https://www.aecc.es/Paginas/PaginaPrincipal.aspx).

Sería interesante abrir cada uno de los links de esas noticias para sacar la foto y el texto completo (solo ponen en la home las dos últimas noticias).

**Comment by fjvela** [comment]
Entiendo que las notificas se quieren mostrar en el home de la aplicación móvil ¿no?

**Comment by AntonioCabreraTornero** [comment]
Eso es

**Comment by fjvela** [comment]
Perfecto, si me dais ok haría lo siguiente: 

- Crear un nuevo método en la API (NewsChannel)
- La aplicación móvil se conectaría a la API para obtener las noticias disponibles

Con esto podríamos cachear las noticias en el server y aparte en un futuro se podrían incluir otras noticias que no estén incluidas en la pagina de la aecc.

**Comment by fjvela** [comment]
Tengo la parte de la API funcionando. Estoy intentando cambiar la parte del móvil, despliego la APK le doy a autenticar pero me da una excepción en la autenticación. ¿Podéis echarme un mano? ¿Me falta algo?

**Comment by AntonioCabreraTornero** [comment]
Pues no detecto ningún problema para loguear, si eres tan amable de confirmarme en que plataforma tratas de iniciar (Android, imagino) y de copiarme la excepción para ver si te falta algo en particular e intentamos así ayudarte. Gracias!
