### ISSUE TITLE
Añadir notificación local cuando te envian un mensaje o te solicitan conversación

### ISSUE THREAD

**Issue by Alfraso** [BraventIT/AeccApp#53]
Había pensado que sería interesante utilizar este plugin:
https://github.com/EgorBo/Toasts.Forms.Plugin

**Comment by AntonioCabreraTornero** [comment]
-

**Comment by AntonioCabreraTornero** [comment]
- [x] Notificaciones locales Android 
- [x] Notificaciones locales iOS
