### ISSUE TITLE
Crear SplashScreen miestras carga la app

### ISSUE THREAD

**Issue by Alfraso** [BraventIT/AeccApp#55]
Sería interesante añadir una SlashScreen tal como aparece en Invision:
https://projects.invisionapp.com/d/main#/projects/prototypes/12441126
(seguramente necesite permiso.. Pedirlos, pero no cambies nada please!!!!)

En el siguiente artículo dicen como hacerlo:
https://xamarinhelp.com/creating-splash-screen-xamarin-forms/

**Comment by AntonioCabreraTornero** [comment]
- [x] UWP 

- [x] Android

- [x] iOS
